# Generated by Django 4.2.11 on 2024-04-23 18:00

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(validators=[booking.models.validate_date]),
        ),
    ]
