# Generated by Django 4.2.11 on 2024-04-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-time', '-date']},
        ),
    ]
