# Generated by Django 4.2.11 on 2024-04-22 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid', message='Please enter valid contact number,digits only, up to 15 allowed.', regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
